### ISSUE TITLE
Does it support xaml ? 

### ISSUE THREAD

**Issue by AfaqSofware** [KSemenenko/LocalizationForXamarinForms#1]
Hello , i would like to thank you for your participation and i think this would be really usefull if it would be complete :) 
so I want to ask :
1. Does it have a support for Xaml ? 
2. How to use this package ?

**Comment by KSemenenko** [comment]
Hi, Thank you for your interest!
Yes, it will support Xaml, now it is in development. 
As an example of the use will be soon, I'm still working on it

**Comment by KSemenenko** [comment]
HI @AfaqSofware !
Please check new release)
