### ISSUE TITLE
Where do we assign the resource files ?

### ISSUE THREAD

**Issue by tombby11** [KSemenenko/LocalizationForXamarinForms#2]
Hello , i am just wondering where do we assign the resource files ? should they have a specific name ? how does that work ?  Could you provide a full smaple with Xaml translation in it ?

**Comment by KSemenenko** [comment]
For XAML https://github.com/KSemenenko/LocalizationForXamarinForms#for-xamarin-forms
The file you can open in any way. important to convey the contents.
in the future, I have something to do with it.

you can see https://github.com/KSemenenko/LocalizationForXamarinForms/blob/master/TestFormsApp/TestFormsApp.Droid/MainActivity.cs
or 
https://github.com/KSemenenko/LocalizationForXamarinForms#example-use
