### ISSUE TITLE
CSV files explained 

### ISSUE THREAD

**Issue by tombby11** [KSemenenko/LocalizationForXamarinForms#3]
Hello there , thanks again for your nice work and I Think you are doing great job, 
For me it is just that using CSV file for translation is kind of not so clear, so can you add to your documentation how to fill this file ? 

one more thing , I was not able to find where shall we put this file , is it on the platform Projects or the PCL ? 
because I Went through your sample Project and I found the CSV file only in the assets of Android but not on the other Projects

**Comment by KSemenenko** [comment]
Hi @tombby11 , thank for showing interest to my library,
For now you can load file from resource like here https://developer.xamarin.com/guides/xamarin-forms/working-with/files/ or here https://forums.xamarin.com/discussion/23804/reading-file-from-pcl
Anyway, you will have to load file manually. 
And then you will need to use it like this:

``` cs
var text =  ReadFileAndGetContent //get file content for your platform
CrossLocalization.Current.LoadLanguagesFromString(text);
```

My project really contains file for Android only. I will add files to all projects.
